### ISSUE TITLE
Bot changes to a less good planet

### ISSUE THREAD

**Issue by D4rkiii** [meepen/salien-bot#149]
I moved to a new planet where all levels (low / mid / hard) are available but the bot moves back to a planet where only low levels are available.
I am using the browser script in chrome with tampermonkey and i am currently level 11.

The console in the dev tools says something like that:
- Nostalgieplanet II zone 0 (0, 0) progress: 0 difficulty: 3
- Leaving planet, no zones left
![image](https://user-images.githubusercontent.com/17470007/42120774-52f5254c-7c21-11e8-83a5-66b86f7f63bf.png)

Greetz
D4rkiii

**Comment by Dontmindme2** [comment]
I have a guess about this one...
Even without a script, I cannot enter that zone (top left corner).  Maybe that is where a boss will spawn in the future and it is currently locked.  I can run the script on other zones of that planet if I start it just as the game is starting in another zone, but it errors out when the game ends.  So, when the script cannot read that planet (because of the bad zone), it defaults to another planet, maybe the oldest planet?  And that planet only has "Low" zones left.

**Comment by KannushiLink** [comment]
For your information:

I changed MAX_LEVEL constant
https://github.com/meepen/salien-bot/blob/27cb7d296809d9acd84077b5d4e8dc759567f0ac/index.user.js#L22

and enable forceLevellingMode
https://github.com/meepen/salien-bot/blob/27cb7d296809d9acd84077b5d4e8dc759567f0ac/index.user.js#L62

But the bot still insist to play on other crap planets instead of the good planet at top-left. I can play manually on it, though.

**Comment by KannushiLink** [comment]
my temporary fix:

add that in function
https://github.com/meepen/salien-bot/blob/27cb7d296809d9acd84077b5d4e8dc759567f0ac/index.user.js#L149

after the bracket in ``if (zone.boss) {``

```
// temporary fix
// the affect zone index is 0 and progress for it is 0
if (idx == 0 && zone.progress == 0.0) {
    continue;
}
```
