### ISSUE TITLE
Stuck in loop leaving planet (Userscript Mode)

### ISSUE THREAD

**Issue by trolloos** [meepen/salien-bot#155]
It just leaves the planet and refreshes the game forever.

https://i.gyazo.com/8d21f54b40cb9f74eb589d686439c5d8.png

**Comment by TheRedStormer** [comment]
i am having the same problem.

**Comment by trolloos** [comment]
This one works for me though:
https://github.com/TehDmitry/salien-bot

**Comment by MatthiasMoore** [comment]
This issue is related to zone 0 being the best zone on a planet resulting in some bad logic on line 122.  
0 in this case is being interpreted as false, making the script believe that the planet is completed.  But even after changing this, there is still some issue loading into zone 0 properly, but it is part of the solution here.

https://github.com/meepen/salien-bot/blob/d82f1a894bcd0f3fb385ba0226d8667b3ee31fe3/index.user.js#L122

**Comment by Spartanul** [comment]
No idea how to change that. :(

**Comment by meepen** [comment]
Is already updated
