### ISSUE TITLE
Valve's take on this

### ISSUE THREAD

**Issue by dusekdan** [meepen/salien-bot#41]
Hello!

Thank you for awesome script - I was actually just thinking about coding something similar but discovered your work and so I will look for the ways to contribute. 

But there are some things that I think should be considered first - I remember when we did something similar few years back with Golden Helm minigame - no one cared, Valve even somewhat supported botting (I know some of Valve employees actually participated in scripting). Did anyone collected Valve's take on this now? Are they still OK with it? Or are users using the script potentially put in danger?

Thank you, if you find the time to reply, I am looking forward to it.

**Comment by Js41637** [comment]
I don't think they ever officially said anything about it not that they ever say anything. I think they are definitely fully aware of what would happen when they made this game, it probably caught them a bit by surprise the first time with how in-depth the auto play scripts went as the 2015 game was much more complex compared to this one. 

To be honest either they really wanted to do something simpler or knew there was no point against trying to protect the game against auto play scripts because this game is ridiculously easy to auto play. You've probably seen some other scripts that don't even play the game at all and just send network requests, the game is so simple that all you really need to do is have a script send a score (roughly 2400) every 120 seconds and the game will accept it.

I don't think it really changes anything though, there are no bonuses for leveling or playing more. The free game reward which you have to be ridiculously lucky to get anyway is just based on time in a level which anyone can do regardless of the script. (I believe)

I think as long as people have fun with the game then they don't really care even though so far there doesn't really seem to be much incentive for this game. The 2015 one was so much popular because it had a bit more depth and it was more of a 'multiplayer' as you worked with heaps of other people in a lobby/room to "click" on all the monsters. It was a bit more team based which I think they kinda tried to do with this one except 99% of people all seem to be in the same group so it's pretty much pointless.

**Comment by meepen** [comment]
Yeah, as far as I'm aware Valve doesn't really care. This script doesn't even do anything but help finish planets, and AFKing on the screen will get you the same chances as far as I know.
